### ISSUE TITLE
The Buffer() constructor has been deprecated.

### ISSUE THREAD

**Issue by HelixFix** [Ayms/torrent-live#4]
> The Buffer() and new Buffer() constructors are not recommended for use due to security and usability concerns. Please use the new Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() construction methods instead. 

https://nodejs.org/fr/docs/guides/buffer-constructor-deprecation/

**Comment by Ayms** [comment]
I know of course, but I like new Buffer, see the fix/hack https://github.com/Ayms/node-Tor/blob/master/lib/node-tor.js/#L84-L103 (not included in torrent-live but easy to do)
